### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by obscurerichard**
A tiny, tiny documentation bug fix. Merge pretty please!

### CODE REVIEW

**Comment by obscurerichard** [comment]
```
lonely pull request
the completist in me pines
for its prompt closure
```

**Comment by obscurerichard** [comment]
```
sadness incarnate
why does the wind blow so cold
please merge pull request
```

**Comment by finitud** [comment]
Apologies for the *ahem* three year delay merging this one, I haven't been checking this account much since leaving tech 👀

**Comment by obscurerichard** [comment]
Thank you for merging my long-standing PR! 

*_You can leave technology as a career, but the good work you have done continues to speak for itself._*

🏆 🥇 ⭐️

**Pull request merged**
