### PR TITLE
Ignore more temporary files

### PR DESCRIPTION
**Pull request by obscurerichard**
Editor swap files are _the worst_ if they pollute your repo. Please merge this trivial fix.

### CODE REVIEW

**Comment by obscurerichard** [comment]
```
a sad tale indeed
the tiniest fix is paused
awaiting your touch
```

**Comment by finitud** [comment]
Done! Which editor is that, btw?

**Comment by obscurerichard** [comment]
`vim` writes a `.filename.swp` file to disk every time you open a file, an "editor swap file" where it records non-saved edits and other session information.

**Comment by obscurerichard** [comment]
And thank you for merging my long-standing PR! 
🏆 🥇 ⭐️

**Pull request merged**
